version: 2.1

executors:
  node8:
    docker:
      - image: circleci/node:8-browsers
  node10:
    docker:
      - image: circleci/node:10-stretch-browsers
  node_latest:
    docker:
      - image: circleci/node:11-stretch-browsers

commands:
  install_firefox:
    description: "Install firefox binary"
    parameters:
      version:
        type: string
    steps:
      - restore_cache:
          key: firefox-bin
          paths:
            - ~/firefox
      - run:
          name: Install Firefox
          command: |
            test -d ~/firefox/<< parameters.version >> && exit 0
            url='https://ftp.mozilla.org/pub/firefox/releases/<< parameters.version >>/linux-x86_64/en-US/firefox-<< parameters.version >>.tar.bz2'
            curl -sSL -o- "$url" | tar xvfj - -C /tmp
            mkdir -p ~/firefox
            mv /tmp/firefox ~/firefox/<< parameters.version >>
      - save_cache:
          key: firefox-bin
          paths:
            - ~/firefox
      - run: echo 'export PATH=~/firefox/<< parameters.version >>:$PATH' >> $BASH_ENV

  npm_install:
    description: "Do npm install and cache node_modules"
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build:
    steps:
      - run:
          name: Install geckodriver
          command: |
            URL='https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz'
            curl -sSLf "$URL" | tar zxv -C /tmp
            /tmp/geckodriver
          background: true

      - checkout
      - npm_install
      - run: npm run lint
      - run: npm run build
      - run: npm test

jobs:
  build_node8:
    executor:
      name: node8
    steps:
      - install_firefox:
          version: "60.0esr"
      - build

  build_node10:
    executor:
      name: node10
    steps:
      - install_firefox:
          version: "60.0esr"
      - build

  build_node_latest:
    executor:
      name: node_latest
    steps:
      - install_firefox:
          version: "60.0esr"
      - build

  deploy:
    executor:
      name: node8
    steps:
      - checkout
      - run:
          name: "Prepare npm account"
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build_node8:
          filters:
            tags:
              only: /^v.*$/
      - build_node10:
          filters:
            tags:
              only: /^v.*$/
      - build_node_latest:
          filters:
            tags:
              only: /^v.*$/
      - deploy:
          requires:
            - build_node8
            - build_node10
            - build_node_latest
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
