name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        node-version: ["14", "16", "18"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: ueokande/setup-firefox@latest
      with:
        firefox-version: latest-esr
    - uses: ueokande/setup-geckodriver@latest
      with:
        geckodriver-version: 0.28.0
    - run: yarn install --immutable
    - run: yarn lint
    - run: yarn build
    - run: Xvfb -ac :99 -screen 0 1280x1024x24 &
    - run: yarn test
      env:
        DISPLAY: :99
    - name: Run examples
      working-directory: examples
      env:
        DISPLAY: :99
      run: |
        yarn install --immutable
        set -x
        node 01_setup_teardown.js
        node 02_webext_api.js
        node 03_webdriver_api.js
        node 04_spy_addon.js

  deploy:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn build
    - name: "Prepare npm account"
      env:
        NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >~/.npmrc
    - run: yarn npm publish
